<?php

/**
 * @file
 *  Implements a feature for domains that you can have multiple variants for the
 *  same domain. For example: example.com/global and example.com/country/china
 *  can be both variants for the example.com domain, and all the urls will be
 *  overwritten to respect that prefix. Moreover, the variant can actually be
 *  another domain, so for example another_domain.com/global/example can be a
 *  variant of the some_domain.example.com
 */

/**
 * Implements hook_menu().
 */
function domain_variants_menu() {
  $items['admin/structure/domain/variants'] = array(
    'title' => 'Domain variants',
    'access arguments' => array('administer domains'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'domain_variants_page',
    'file' => 'domain_variants.admin.inc',
  );
  $items['admin/structure/domain/variants/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/domain/variants/%domain'] = array(
    'title' => 'Edit domain variants',
    'access arguments' => array('administer domains'),
    'type' => MENU_CALLBACK,
    'page callback' => 'domain_variants_admin',
    'page arguments' => array(4),
    'file' => 'domain_variants.admin.inc',
  );
  $items['admin/structure/domain/variants/%domain/edit/%domain_variants'] = array(
    'title' => 'Edit domain variant',
    'access callback' => 'domain_variants_edit_access',
    'access arguments' => array(4, 6),
    'type' => MENU_CALLBACK,
    'page callback' => 'domain_variants_admin',
    'page arguments' => array(4, 6),
    'file' => 'domain_variants.admin.inc',
  );
  $items['admin/structure/domain/variants/%domain/delete/%domain_variants'] = array(
    'title' => 'Delete domain variant',
    'access callback' => 'domain_variants_edit_access',
    'access arguments' => array(4, 6),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('domain_variants_delete_confirm', 4, 6),
    'file' => 'domain_variants.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function domain_variants_init() {
  global $_domain_variant, $language;
  if (_domain_variant_is_plain_request() && !empty($_domain_variant)) {
    module_load_include('inc', 'domain_variants');
    if ($redirect_langcode = _domain_variant_check_language($_domain_variant->variant_id, $language->language)) {
      $languages = language_list();
      $query = drupal_get_query_parameters();
      if (!empty($_GET['destination'])) {
        unset($_GET['destination']);
      }
      drupal_goto(current_path(), array(
        'query' => $query,
        'language' => $languages[$redirect_langcode],
      ));
    }
  }
}

/**
 * Access handler for editing and deleting domain variants.
 */
function domain_variants_edit_access($domain, $variant) {
  // We must check that the domain id of the variant is correct.
  if ($variant->domain_id != $domain['domain_id']) {
    return FALSE;
  }
  return user_access('administer domains');
}

/**
 * Implement hook_enable().
 *
 * Register domain_variants with domain bootstrap so we can use domain_bootstrap
 * hooks.
 */
function domain_variants_enable() {
  domain_bootstrap_register();
}

/**
 * Implement hook_disable().
 */
function domain_variants_disable() {
  domain_bootstrap_register();
}

/**
 * Implements hook_domain_bootstrap_lookup().
 */
function domain_variants_domain_bootstrap_lookup($domain) {
  global $_domain_variant;
  $_domain_variant = NULL;
  $full_path = $_SERVER['HTTP_HOST'] . '/' . ltrim($_GET['q'], '/');
  $words = explode('?', $full_path);
  // Make sure that the search path ends with "/" because we append a "/" to the
  // path that we search for in the query. This is implemented like that to
  // avoid the issues introduced by the variant prefixes. For example, if we
  // have two variants: example.com/variant1 and example.com/variant11, because
  // the first variant is basically a prefix of the second one, we may get the
  // wrong variant when visiting example.com/variant11.
  $search_path = rtrim($words[0], '/') . '/';
  $query = db_select('domain_variants', 'variants');
  $query->fields('variants', array('variant_id', 'domain_id', 'path'));
  $query->addExpression('LOCATE(CONCAT(path, \'/\'), :path_search)', 'path_search', array(':path_search' => $search_path));
  $query->having('path_search = 1');
  $domain_variant = $query->execute()->fetch();
  if ($domain_variant) {
    $domain = db_select('domain', 'domain')->fields('domain', array('domain_id', 'subdomain', 'sitename', 'scheme', 'valid', 'weight', 'is_default', 'machine_name'))->condition('domain.domain_id', $domain_variant->domain_id)->execute()->fetch(PDO::FETCH_ASSOC);
    // Fully load the domain variant into the global variable.
    $_domain_variant = domain_variants_load($domain_variant->variant_id);
    // We also have to remove all the parts that come after "/" from the variant
    // so that the language for example will be handled correctly, and also, to
    // avoid the menu not found errors.
    $words = explode('/', $domain_variant->path);
    array_shift($words);
    if (count($words)) {
      $search = implode('/', $words);
      $q = rtrim($_GET['q'], '/') . '/';
      // Remove the variant prefix, but only from the begining of the q value.
      // For example, if we have the path: usa/en/blog/article-usa/ then only
      // the first 'usa/' has to be removed (if the prefix of the domain is
      // 'usa/').
      if (strpos($q, $search . '/') === 0) {
        $q = substr($q, strlen($search . '/'));
      }
      // Finally, restore the q and remove the trailing slash.
      $_GET['q'] = rtrim($q, '/');
    }
  }
  return $domain;
}

/**
 * Implements hook_module_implements_alter().
 */
function domain_variants_module_implements_alter(&$implementations, $hook) {
  // The url_outbound_alter() hook must be called at the end of the queue,
  // because the prefix for the domain variants has to be added at the end.
  if ($hook == 'url_outbound_alter') {
    $group = $implementations['domain_variants'];
    unset($implementations['domain_variants']);
    $implementations['domain_variants'] = $group;
  }
}

/**
 * Implements hook_pathologic_alter().
 */
function domain_variants_pathologic_alter(&$url_params, &$parts, $cached_settings) {

  if (!empty($cached_settings['is_file'])) {

    // Do not process file URLs being corrected by the pathologic module.
    $url_params['options']['skip_domain_variant'] = TRUE;
  }
  else {

    // The pathologic module parses internal URLs that provided as an absolute
    // URL. It tries to remove the language prefix from path and pass the
    // corresponding language object to url() as the "language" option.
    // However, the pathologic module knows nothing about the possible domain
    // variant prefix, so it fails with language detection, and in the end we
    // have double prefix in the URL. For example:
    // schweiz/de-ch/schweiz/de-ch/file/88/download
    // Fix this:
    //   1. Strip a domain variant prefix from the path and pass the domain
    //      variant object to the url() as the "domain_variant" option.
    //   2. Repeat the language detection.
    if (isset($parts['host'])) {
      static $all_domain_variants;
      if (!isset($all_domain_variants)) {
        $all_domain_variants = array();
        $variant_ids = db_select('domain_variants', 'dv')
          ->fields('dv', array('variant_id'))
          ->execute()
          ->fetchCol();
        foreach ($variant_ids as $variant_id) {
          $all_domain_variants[$variant_id] = domain_variants_load($variant_id);
        }
      }
      foreach ($all_domain_variants as $domain_variant) {
        if ($parts['host'] == $domain_variant->base_url &&
          isset($domain_variant->prefix) &&
          strpos($url_params['path'], $domain_variant->prefix . '/') === 0) {
          $url_params['options']['domain_variant'] = $domain_variant;
          $url_params['path'] = $parts['path'] = substr($url_params['path'], strlen($domain_variant->prefix) + 1);
          // Now we do the same that _pathologic_replace() does.
          if (module_exists('locale')) {
            require_once DRUPAL_ROOT . '/includes/language.inc';
            list($language_obj, $path) = language_url_split_prefix($parts['path'], language_list());
            if ($language_obj) {
              $url_params['path'] = $parts['path'] = $path;
              $url_params['options']['language'] = $language_obj;
            }
          }
          break;
        }
      }
    }
  }
}

/**
 * Rewrites the URLs by prepending the domain_variant if needed.
 */
function domain_variants_url_outbound_alter(&$path, &$options, $original_path) {
  global $_domain, $_domain_variant;

  // Check first if we have to skip the rewrite. In some case (for example for
  // external links) we do not want to have the domain variant.
  if (!empty($options['skip_domain_variant']) || !empty($options['external'])) {
    return;
  }
  // If we are on a domain variant, or if we have an domain_variant in the
  // options
  if (empty($options['domain_variant']) && !empty($_domain_variant)) {
    $options['domain_variant'] = $_domain_variant;
  }
  if (!empty($options['domain_variant'])) {
    if (!empty($options['domain_variant']->prefix)) {
      $options['prefix'] = !empty($options['prefix']) ? $options['domain_variant']->prefix . '/' . $options['prefix'] : $options['domain_variant']->prefix . '/';
    }
    if (!empty($options['domain_variant']->base_url)) {
      // @todo: at the moment, we use only http:// as scheme, but this could
      // should maybe be changed to use the scheme of the domain.
      $options['base_url'] = 'http://' . $options['domain_variant']->base_url;
      $options['absolute'] = TRUE;
    }
  }
}

/**
 * Implements hook_i18n_translate_path_alter().
 */
function domain_variants_i18n_translate_path_alter(&$items, $path) {
  global $_domain;
  // Some translations may be available only on certain domains.
  if (module_exists('domain_locale')) {
    $domain_locale_list = domain_locale_list();
    foreach ($items as $lang_code => $item) {
      foreach ($domain_locale_list as $dom_id => $domain_locale) {
        if (!empty($domain_locale[$lang_code])) {
          if ($_domain['domain_id'] != $dom_id) {
            $domain = domain_load($dom_id);
            // Currently, only alter the URL if we have a variant.
            if (!empty($domain['variants'])) {
              $items[$lang_code]['domain_variant'] = reset($domain['variants']);
            }
            else {
              // If the domain has no variants, then just skip them.
              $items[$lang_code]['skip_domain_variant'] = TRUE;
            }
          }
          break;
        }
      }
    }
  }
}

/**
 * Returns the language of a variant.
 *
 * @param object $variant
 *  The variant.
 */
function domain_variants_get_variant_language($variant) {
  $enabled_languages = language_list('enabled');
  $enabled_languages = $enabled_languages[1];
  if (!empty($enabled_languages)) {
    // First, if the variant has a "languages" attribute, check that one.
    if (!empty($variant->languages)) {
      foreach ($variant->languages as $key => $value) {
        if (!empty($enabled_languages[$key])) {
          // We found the language, so return it.
          return $enabled_languages[$key];
        }
      }
    }
  }
  global $language;
  // If we are here, just return the current language.
  return $language;
}

/**
 * Implements hook_block_info().
 */
function domain_variants_block_info() {
  $blocks['domain_variants_switcher'] = array(
    'info' => t('Domain variants switcher'),
    // If the links in the block have to reflect the current page, then the
    // block must not be cached.
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['domain_variants_links_switcher'] = array(
    'info' => t('Domain variants links switcher'),
    // If the links in the block have to reflect the current page, then the
    // block must not be cached.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function domain_variants_block_view($delta = '') {
  $blocks = array();
  switch ($delta) {
    case 'domain_variants_switcher': {
      $blocks['content'] = drupal_get_form('domain_variants_switcher_form');
      break;
    }
    case 'domain_variants_links_switcher': {
      $blocks['content'] = domain_variants_links_switcher();
      break;
    }
  }
  return $blocks;
}

/**
 * Shows the domain variants switcher as links.
 *
 * @param array $domains
 *  An array with the domains.
 */
function domain_variants_links_switcher($domains = array()) {
  global $language_url, $_domain_variant;
  if (empty($domains)) {
    $domains = domain_domains();
  }
  $links = array();
  foreach ($domains as $domain) {
    // Skip the disabled domains, the domain_domains() returns all the results.
    if (!$domain['valid'] && !user_access('access inactive domains')) {
      continue;
    }
    // If the domain has variants, put them as options, otherwise put the domain
    // itself.
    if (!empty($domain['variants'])) {
      foreach ($domain['variants'] as $variant) {
        // If the languages are not set, it is possible that the variant was not
        // fully loaded, so do it here.
        if (!isset($variant->languages)) {
          $variant = domain_variants_load($variant->variant_id, TRUE);
        }
        $class = array();
        if (!empty($variant->countries)) {
          $class = array_keys($variant->countries);
        }
        $class[] = 'domain-' . $variant->domain_id;
        $path = current_path();
        $lang = domain_variants_get_variant_language($variant);
        // Add the active class.
        if (($path == $_GET['q'] || ($path == '<front>' && drupal_is_front_page()))
            // @todo (alex): do we really need this language condition?
            //&& (empty($lang) || $lang->language == $language_url->language)
            && (empty($_domain_variant) || $_domain_variant->variant_id == $variant->variant_id)) {
          $class[] = 'active';
        }
        $links[] = array('data' => l($variant->name, $path, array('language' => $lang, 'domain_variant' => $variant)), 'class' => $class);
      }
    }
    else {
      $links[] = l($domain['sitename'], domain_check_scheme($domain['scheme']). '://' . $domain['subdomain'] . base_path() . current_path());
    }
  }
  return array(
    '#theme' => 'item_list',
    '#items' => $links,
    '#attributes' => array('class' => array('language-switcher-locale-url')),
  );
}

/**
 * Form constructor for the domain variants switcher.
 */
function domain_variants_switcher_form($form, &$form_state, $domains = array()) {
  // We will print all the variants of a domain, if it has, otherwise
  // we will print only the domain.
  if (empty($domains)) {
    $domains = domain_domains();
  }
  $form['domain_variant_swicher']['#type'] = 'select';
  // Construct the options.
  $options = array();
  foreach ($domains as $domain) {
    // Skip the disabled domains, the domain_domains() returns all the results.
    if (!$domain['valid'] && !user_access('access inactive domains')) {
      continue;
    }
    // If the domain has variants, put them as options, otherwise put the domain
    // itself.
    if (!empty($domain['variants'])) {
      foreach ($domain['variants'] as $variant) {
        $options['v_' . $variant->variant_id] = $variant->name;
        $path = current_path();
        if ($path == variable_get('site_frontpage', 'node')) {
          $path = '';
        }
        // Put also the hidden elements, the same concept as in the
        // lang_dropdown module.
        $form['v_' . $variant->variant_id] = array(
          '#type' => 'hidden',
          '#default_value' => check_plain(url($path, array(
            'language' => domain_variants_get_variant_language($variant),
            'domain_variant' => $variant,
          ))),
          '#domain_variant' => $variant,
        );
      }
    }
    else {
      $options['d_' . $domain['domain_id']] = $domain['sitename'];
      $form['d_' . $domain['domain_id']] = array(
        '#type' => 'hidden',
        '#default_value' => check_plain(domain_check_scheme($domain['scheme'])
            . '://' . $domain['subdomain'] . base_path() . current_path()),
      );
    }
  }
  $form['domain_variant_swicher']['#options'] = $options;
  // Put the default value in the dropdown.
  global $_domain;
  if (!empty($_domain['variants'])) {
    global $_domain_variant;
    if (!empty($form['domain_variant_swicher']['#options']['v_' . $_domain_variant->variant_id])) {
      $form['domain_variant_swicher']['#default_value'] = 'v_' . $_domain_variant->variant_id;
    }
  }
  else {
    $form['domain_variant_swicher']['#default_value'] = 'd_' . $_domain['domain_id'];
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
    '#attributes' => array('class' => array('ctools-auto-submit-click')),
  );
  $form['#attached']['js'] = array(ctools_attach_js('auto-submit'));
  $form['#attributes'] = array('class' => array('ctools-auto-submit-full-form'));
  return $form;
}

/**
 * Submit handler for the domain variants switcher form.
 */
function domain_variants_switcher_form_submit(&$form, &$form_state) {
  $redirect_url = $form_state['values'][$form_state['values']['domain_variant_swicher']];
  $form_state['redirect'] = array($redirect_url, array('skip_domain_variant' => TRUE));
}

/**
 * Loads a domain variant by its id.
 */
function domain_variants_load($variant_id, $reset = FALSE) {
  static $variants = array();
  if (!isset($variants[$variant_id]) || $reset) {
    $variants[$variant_id] = db_select('domain_variants', 'dm')->fields('dm')->condition('dm.variant_id', $variant_id)->range(0, 1)->execute()->fetch();
    if ($variants[$variant_id]) {
      $words = explode('/', $variants[$variant_id]->path);
      $base = array_shift($words);
      if ($words) {
        $variants[$variant_id]->prefix = implode('/', $words);
        $variants[$variant_id]->base_url = $base;
      }
      // This function is called from the domain_variants_domain_bootstrap_lookup()
      // and if we will call any module_invoke_all() here, then the registry will
      // be saved wrong later during the request. Unless, we put the module_invoke
      // outside of the static check, but then the static cache is not so useful
      // anymore.
      // As a hack at the moment, only the dv_georedirect module, if it exists,
      // implements this hook, so call it directly until we find a solution.
      if (module_exists('dv_georedirect') && function_exists('dv_georedirect_domain_variants_load')) {
        dv_georedirect_domain_variants_load($variants[$variant_id]);
      }
    }
  }
  return $variants[$variant_id];
}

/**
 * Saves a domain variant.
 */
function domain_variants_save($domain_variant) {
  $update = array();
  if (!$domain_variant->is_new && $domain_variant->variant_id) {
    $update = array('variant_id');
  }
  // Insert the main details.
  drupal_write_record('domain_variants', $domain_variant, $update);

}

/**
 * Deletes a domain variant.
 */
function domain_variants_delete($variant_id) {
  db_delete('domain_variants')->condition('variant_id', $variant_id)->execute();
}

/**
 * Implements hook_domain_load().
 */
function domain_variants_domain_load(&$domain) {
  // If the domain has variants, then attach them.
  $query = db_select('domain_variants', 'variants')->fields('variants', array('variant_id'))->condition('variants.domain_id', $domain['domain_id']);
  $result = $query->execute()->fetchAll();
  foreach ($result as $data) {
    $domain['variants'][$data->variant_id] = domain_variants_load($data->variant_id);
  }
}

/**
 * Implements hook_domain_path().
 */
function domain_variants_domain_path($domain_id, &$path, &$options, $original_path) {
  global $_domain_variant;
  // If we are trying to create a link to another domain, make sure we either
  // just remove any variant from it, or use the correct variant.
  if (!empty($_domain_variant)  && $domain_id != $_domain_variant->domain_id) {
    // For the moment, we do not handle also the case with domain variants, so
    // just use the original path when the domain path we have to show is not
    // on the current domain.
    // The source issue is this one: http://jira.amazeelabs.com/browse/VET-50
    // Do it only for admin pages, because in some cases this can trigger a
    // redirect loop (SIG-238).
    if (strpos($original_path, 'admin/') === 0) {
      $path = $original_path;
    }

    /*$dom = domain_load($domain_id);
    if (empty($dom['variants'])) {
      $path = $original_path;
    }*/
  }
}

/**
 * Returns all the domain variants that are assigned to a domain.
 */
function domain_variants_loockup($domain_id) {
  static $variants = array();
  if (!isset($variants[$domain_id])) {
    $variants[$domain_id] = array();
    $query = db_select('domain_variants', 'dm')->fields('dm', array('variant_id'))->condition('dm.domain_id', $domain_id);
    $result = $query->execute()->fetchAll();
    foreach ($result as $data) {
      $variants[$domain_id][$data->variant_id] = domain_variants_load($data->variant_id);
    }
  }
  return $variants[$domain_id];
}
/**
 * Implements hook_xmlsitemap_context_url_options_alter().
 *
 * Alter xml sitemap url to use domain variant instead of domain link. Requires
 * domain_xmlsitemap module which provides domain context for domains
 */
function domain_variants_xmlsitemap_context_url_options_alter(array &$options, array $context) {
  if (!empty($context['domain']) && !empty($context['domain_variant'][$context['domain']])) {
    $options['domain_variant'] = domain_variants_load($context['domain_variant'][$context['domain']]);
  }
  else {
    $options['skip_domain_variant'] = true;
  }
}

/**
 * Implements hook_xmlsitemap_context_info().
 */
function domain_variants_xmlsitemap_context_info() {
  $context['domain_variant'] = array(
    'label' => t('Domain variant'),
    'default' => null,
  );
  return $context;
}

/**
 * Implements hook_form_FORM_ID_alter() for xmlsitemap_sitemap_edit_form().
 *
 * Adds an option for selecting domain variants as part of xmlsitemap context.
 */
function domain_variants_form_xmlsitemap_sitemap_edit_form_alter(&$form, $form_state) {
  // Disable this when domain_xml_sitemap is not enabled
  if (!module_exists('domain_xmlsitemap')) {
    return;
  }

  $domain_variants = array_keys(db_select('domain_variants', 'dv')
    ->fields('dv', array('variant_id'))
    ->execute()
    ->fetchAllAssoc('variant_id'));

  // Nothing to do if no variants available
  if (empty($domain_variants)) {
    return;
  }

  // Trick element order (in case this hook get called first)
  // @todo: do it properly (with form #process maybe?)
  if (!isset($form['context']['domain'])) {
    $form['context']['domain'] = array();
  }

  // Create the form element for selecting domain variants
  $form['context']['domain_variant'] = array();
  $form_element = &$form['context']['domain_variant'];

  // Start by adding options grouped by domain id
  foreach($domain_variants as $variant_id) {
    $domain_variant = domain_variants_load($variant_id);
    $domain_id = $domain_variant->domain_id;

    $form_element[$domain_id]['#options'][$variant_id] = $domain_variant->path;
  }

  // Expand form element for each domain id (title + other Form API attributes)
  foreach($form_element as $domain_id => $variants_element) {
    $domain = domain_load($domain_id);

    // Required attributes
    $form_element[$domain_id]['#title'] = t('Domain variant to use for !domain', array('!domain' => $domain['sitename']));
    $form_element[$domain_id]['#type'] = 'radios';

    // Add an empty option to allow user to generate xmlsitemaps without variants
    $form_element[$domain_id]['#options'] =
      array(0 => $domain['subdomain'] . ' (no variant)')
      + $form_element[$domain_id]['#options'];

    // Show only the domain variants of the current domain
    $form_element[$domain_id]['#states'] = array(
      'visible' => array(
        ':input[name="context[domain]"]' => array('value' => $domain_id),
      ),
    );

    // Default value
    if (isset($form['#sitemap']->context['domain_variant'][$domain_id])) {
      $form_element[$domain_id]['#default_value'] =
        $form['#sitemap']->context['domain_variant'][$domain_id];
    }
  }

  array_unshift($form['#validate'], '_domain_variants_cleanup_xmlsitemap_sitemap_edit_form');
}

/**
 * Cleanup submitted form values for xmlsitemap_sitemap_edit_form() by removing
 * domain variant selection for domains other than selected one.
 */
function _domain_variants_cleanup_xmlsitemap_sitemap_edit_form(&$form, &$form_state) {
  if (!empty($form_state['values']['context']['domain_variant'])) {
    $domain_variants = &$form_state['values']['context']['domain_variant'];
    $selected_domain = $form_state['values']['context']['domain'];

    foreach($domain_variants as $domain_id => $value) {
      if (!empty($value) && $domain_id != $selected_domain) {
        $domain_variants[$domain_id] = null;
      }
    }

    // Remove all domain id that are empty, except 0 (no domain variant)
    // @see: http://php.net/manual/en/function.array-filter.php#111091
    $domain_variants = array_filter($domain_variants, 'strlen');
  }
}

/**
 * Implements hook_xmlsitemap_context().
 */
function domain_variants_xmlsitemap_context() {
  global $_domain, $_domain_variant;

  if (!empty($_domain_variant)) {
    return array(
      'domain_variant' => array(
        $_domain_variant->domain_id => $_domain_variant->variant_id
      )
    );
  }
  elseif (!empty($_domain)) {
    return array(
      'domain_variant' => array(
        $_domain['domain_id'] => '0', // STRING OR HASH WILL NOT MATCH
      ),
    );
  }

  return array();
}

/**
 * Detects whether current request is "plain".
 */
function _domain_variant_is_plain_request() {
 return (
   !drupal_is_cli()
   && (empty($_SERVER['HTTP_X_REQUESTED_WITH']) || strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) != 'xmlhttprequest')
   && in_array($_SERVER['REQUEST_METHOD'], array('GET', 'HEAD'))
 );
}
